"""Parity verification for the two ``csm_env`` copies in this workspace.

There is a working copy at the repository root and a copy inside
``EnterpriseOps-Gym``. Because the benchmark resolves ``csm_env`` relative to
its own directory, a stale gym-local copy would silently mean Condition B is
*not* the frozen intervention.

This module hashes both trees and fails closed on divergence.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Tuple, Union

PathLike = Union[str, Path]

#: Caches and generated bytecode are not part of the contract.
_EXCLUDED_DIRS = frozenset({"__pycache__", ".pytest_cache", ".mypy_cache"})


def sha256_file(path: PathLike) -> str:
    """Return the SHA-256 digest of one file's raw bytes."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_text_normalized(path: PathLike) -> str:
    """Return the SHA-256 digest of a text file with line endings normalized to LF.

    Content pins must be reproducible across platforms. The same source file
    checked out on Windows (CRLF) and on Linux (LF) has different raw bytes but
    identical content, and a default ``core.autocrlf`` checkout rewrites one
    into the other without ever showing up as a working-tree change. Hashing the
    LF-normalized text makes a pin mean *"this content"* instead of *"this
    platform's line endings"*.

    Use :func:`sha256_file` for genuinely binary payloads (archives, images),
    where byte-exactness is the point.
    """
    data = Path(path).read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(data).hexdigest()


def hash_package(package_dir: PathLike) -> Dict[str, str]:
    """Hash every Python module in a package, keyed by dotted-ish path."""
    root = Path(package_dir)
    if not root.is_dir():
        raise ValueError(f"Package directory does not exist: {root}")
    hashes: Dict[str, str] = {}
    for path in sorted(root.rglob("*.py")):
        if any(part in _EXCLUDED_DIRS for part in path.parts):
            continue
        hashes[path.relative_to(root).as_posix()] = sha256_file(path)
    if not hashes:
        raise ValueError(f"No Python modules found under {root}")
    return hashes


@dataclass(frozen=True)
class ParityReport:
    """Result of comparing two ``csm_env`` trees."""

    root_package: str
    gym_package: str
    only_in_root: Tuple[str, ...]
    only_in_gym: Tuple[str, ...]
    changed: Tuple[str, ...]
    identical_count: int

    @property
    def is_identical(self) -> bool:
        return not (self.only_in_root or self.only_in_gym or self.changed)

    def as_dict(self) -> Dict[str, object]:
        return {
            "root_package": self.root_package,
            "gym_package": self.gym_package,
            "only_in_root": list(self.only_in_root),
            "only_in_gym": list(self.only_in_gym),
            "changed": list(self.changed),
            "identical_count": self.identical_count,
            "is_identical": self.is_identical,
        }


def compare_csm_env_copies(
    root_package: PathLike = "csm_env",
    gym_package: PathLike = "EnterpriseOps-Gym/csm_env",
) -> ParityReport:
    """Compare the two ``csm_env`` copies module by module.

    Raises:
        ValueError: If either directory is missing or contains no modules.
    """
    root_hashes = hash_package(root_package)
    gym_hashes = hash_package(gym_package)
    only_root = tuple(sorted(set(root_hashes) - set(gym_hashes)))
    only_gym = tuple(sorted(set(gym_hashes) - set(root_hashes)))
    changed = tuple(
        sorted(
            name
            for name in set(root_hashes) & set(gym_hashes)
            if root_hashes[name] != gym_hashes[name]
        )
    )
    identical = len(set(root_hashes) & set(gym_hashes)) - len(changed)
    return ParityReport(
        root_package=str(root_package),
        gym_package=str(gym_package),
        only_in_root=only_root,
        only_in_gym=only_gym,
        changed=changed,
        identical_count=identical,
    )


def require_parity(
    root_package: PathLike = "csm_env",
    gym_package: PathLike = "EnterpriseOps-Gym/csm_env",
) -> ParityReport:
    """Compare the copies and raise when they diverge.

    Raises:
        ValueError: With the exact list of diverging modules.
    """
    report = compare_csm_env_copies(root_package, gym_package)
    if not report.is_identical:
        raise ValueError(
            "csm_env copies diverged; Condition B would not be the frozen intervention. "
            f"only_in_root={list(report.only_in_root)}, "
            f"only_in_gym={list(report.only_in_gym)}, changed={list(report.changed)}"
        )
    return report
